---
resources:
- &ponyc-docker-latest
  name: ponyc-docker-latest
  type: docker-image
  source:
    repository: ponylang/ponyc
    tag: latest

<%
@projects = %w{
  ast
  capnp
  inspect
  llvm
  pegasus
  rope
  sodium
  stable
  unsafe
  zmq
}.map { |n| { name: n } }

@projects.each do |project|
  project[:pre] = case project[:name]
  when "sodium" then "apt-get update && apt-get install -y libsodium-dev &&"
  else               ""
  end

  project[:run] = case project[:name]
  when "stable" then "make && make install"
  else               "cd src/#{project[:name]}/test && ponyc && ./test"
  end
end
%>
<% for @project in @projects %>
- name: pony-<%= @project[:name] %>-git
  type: git
  source:
    uri: https://github.com/jemc/pony-<%= @project[:name] %>
    branch: master
<% end %>

jobs:
<% for @project in @projects %>
- name: pony-<%= @project[:name] %>
  public: true
  serial: true
  plan:
  - get: ponyc-docker-latest
    trigger: true
  - get: pony-<%= @project[:name] %>-git
    trigger: true
  - task: pony-<%= @project[:name] %>-test
    config:
      platform: linux
      image_resource: *ponyc-docker-latest
      inputs:
      - name: pony-<%= @project[:name] %>-git
        path: src
      run:
        path: sh
        args: ["-c", "<%= @project[:pre] + " " + @project[:run] %>"]
<% end %>
